### ISSUE TITLE
[Question] How do I use this on newer Swift projects?

### ISSUE THREAD

**Issue by mohsin** [DoubleSymmetry/XNavigation#2]
I created a new SwiftUI project with SwiftUI App lifecycle that doesn't come with the SceneDelegate object. I merely get this as the entry point. How do I use the library here?

```
@main
struct AcmeApp: App {
    var body: some Scene {
        WindowGroup {
            ContentScreen()
        }
    }
}
```

**Comment by dcvz** [comment]
Great question @mohsin ! I'll try to setup such a project, are you able to generate a new project that does use UIKit life cycle?

**Comment by tnmendes** [comment]
@mohsin you can add SceneDelegate and AppDelegate to SwiftUI project.
Here is how to do that:
https://www.fivestars.blog/articles/app-delegate-scene-delegate-swiftui/

**Comment by mohsin** [comment]
Ok cool. Will try it out and let you know if I face issues. Thanks 🙂
